services:
  zabbix:
    image: zabbix/zabbix-server-mysql:alpine-7.0.0
    depends_on:
      - db-mysql
    restart: on-failure
    container_name: zabbix-01
    init: true
    ports:
      - "10051:10051"
    environment:
      - MYSQL_USER=${USR}
      - MYSQL_PASSWORD=${PASS}
      - DB_SERVER_DBNAME=${DATABASE}
      - DB_SERVER_HOST="172.16.1.7"
      - DB_SERVER_PORT=3306
    entrypoint: [top]
    networks:
      net_zabbix:
        ipv4_address: 172.16.1.5

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - zabbix
    restart: on-failure
    container_name: nginx
    networks:
      net_zabbix:
        ipv4_address: 172.16.1.6

  db-mysql:
    container_name: db-mysql
    image: mysql:lts
    ports:
      - "3306:3306"
#    entrypoint: [env]
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="no"
      - MYSQL_USER=${USR}
      - MYSQL_PASSWORD=${PASS}
      - MYSQL_DATABASE=${DATABASE}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      net_zabbix:
        ipv4_address: 172.16.1.7

networks:
  net_zabbix:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
