services:

  zabbix:
    image: zabbix/zabbix-server-mysql:alpine-7.0.0
    user: root
    depends_on:
      - db-mysql
    restart: unless-stopped
    container_name: zabbix-server
    tty: true
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=db-mysql
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USR}
      - MYSQL_PASSWORD=${PASS}
      - MYSQL_ROOT_PASSWORD=root_pwd
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
    networks:
      net_zabbix:
        ipv4_address: 172.16.1.5
    volumes:
      - /opt/zabbix/data:/var/lib/zabbix

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.0.0
    user: root
    ports:
      - "80:8080"
    depends_on:
      - zabbix
      - db-mysql
    restart: unless-stopped
    container_name: web-zabbix
    tty: true
    environment:
      - DB_SERVER_HOST=db-mysql
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USR}
      - MYSQL_PASSWORD=${PASS}
      - MYSQL_ROOT_PASSWORD=root_pwd
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
    networks:
      net_zabbix:
        ipv4_address: 172.16.1.6
    configs:
     - source: zabbix-web
       target: /etc/nginx/http.d/nginx.conf
       mode: 0755

  db-mysql:
    container_name: db-mysql
    tty: true
    image: mysql:8.0-oracle
    user: root
    command:
      - mysqld
      - --skip-mysqlx
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      # Only during upgrade from versions prior 6.4 and new installations (schema deployment)
      - --log_bin_trust_function_creators=1
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USR}
      - MYSQL_PASSWORD=${PASS}
      - MYSQL_ROOT_PASSWORD=root_pwd
      - character-set-server=utf8
      - collation-server=utf8_bin
      - default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      net_zabbix:
        ipv4_address: 172.16.1.7
    volumes:
      - /opt/zabbix/mysql.data:/var/lib/mysql

  java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-7.0.0
    user: root
    restart: unless-stopped
    container_name: zabbix-java-gateway
    tty: true
    networks:
      net_zabbix:
        ipv4_address: 172.16.1.8

networks:
  net_zabbix:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

configs:
  zabbix-web:
    file: /opt/zabbix/nginx.conf
