- name: Add Docker repo
  yum_repository:
    name: docker
    baseurl: https://download.docker.com/linux/centos/9/x86_64/stable/
    description: Official Docker repo
    gpgcheck: no

- name: Install latest version
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: yes
    state: latest

- name: Start Docker
  systemd:
    name: docker
    state: started
    enabled: yes

#- name: Add user to Docker group #Not recommended
#  user:
#    name: '{{ lookup('ansible.builtin.env', 'USER') }}'
#    groups: docker
#    append: yes
#  ignore_errors: true
