- name: Create Wazuh workdir
  become: true
  file:
    path: '{{ workdir }}'
    state: directory
    mode: 0755

- name: Clone Wazuh repo
  git:
    repo: 'https://github.com/wazuh/wazuh-docker.git'
    dest: '{{ workdir }}'
    version: v4.8.1
    single_branch: yes

- name: set vm.max_map_count to 262144 in sysctl
  sysctl: name={{ item.key }} value={{ item.value }}
  with_items:
    - { key: "vm.max_map_count", value: "262144" }

- name: Run the certificate creation script
  shell: docker compose -f generate-indexer-certs.yml run --rm generator
  args:
    chdir: '{{ workdir }}/single-node'

- name: Add wazuh systemd service file
  template:
    src: wazuh.j2
    dest: /etc/systemd/system/wazuh.service
    mode: 0755

- name: Start wazuh systemd service
  systemd:
    name: wazuh
    enabled: yes
    state: started
    daemon_reload: yes
