- name: Create Wazuh workdir
  file:
    path: '{{ workdir }}'
    state: directory
    mode: 0755

- name: Copy basic configs to workdir
  copy:
    src: "{{ role_path }}/files/config"
    dest: "{{ workdir }}/config"
    mode: 0744

- name: Copy compose files
  template:
    src: "{{ item }}"
    dest: "{{ workdir }}/{{ item.split('.') | first | basename }}.yml"
  with_items:
      - "{{ role_path }}/templates/docker-compose.j2"
      - "{{ role_path }}/templates/generate-indexer-certs.j2"

- name: set vm.max_map_count to 262144 in sysctl
  sysctl: name={{ item.key }} value={{ item.value }}
  with_items:
    - { key: "vm.max_map_count", value: "262144" }

- name: Check if certs exists
  stat:
    path: "{{ workdir }}/config/wazuh_indexer_ssl_certs"
  register: ssl_certs

- name: Run the certificate creation script
  shell: docker compose -f generate-indexer-certs.yml run --rm generator
  args:
    chdir: '{{ workdir }}'
  when: not ssl_certs.stat.exists

- name: Run wazuh server
  shell: docker compose up -d
  args:
    chdir: '{{ workdir }}'
