---
# tasks file for install_zabbix
- name: Add zabbix work directory on remote/local host
  file:
    path: /opt/zabbix
    state: directory
    mode: 0755

- name: Copy .env file
  template:
    src: env.j2
    dest: /opt/zabbix/.env
    mode: 0755

- name: Copy compose file
  template:
    src: docker-compose.j2
    dest: /opt/zabbix/docker-compose.yml
    mode: 0755
  notify: Restart zabbix stack

- name: Copy zabbix conf file
  template:
    src: zabbix_server.j2
    dest: /opt/zabbix/zabbix_server.conf
    mode: 0755
  notify: Restart zabbix server

- name: Create nginx config file from template
  template:
    src: nginx.j2
    dest: /opt/zabbix/nginx.conf
    mode: 0755
  notify: Restart zabbix web

- name: Add zabbix systemd service file
  copy:
    src: zabbix.service
    dest: /etc/systemd/system

- name: Start zabbix systemd service
  systemd:
    name: zabbix
    enabled: yes
    state: started
    daemon_reload: yes
