---
- name: Install Docker
  hosts: all
  become: yes

  roles:
    - { role: install_docker, when: inventory_hostname is "master" }
    - { role: install_wazuh, when: inventory_hostname is "master" }
