---
- name: Install Docker
  hosts: all
  become: yes

  roles:
    - { role: install_docker, when: inventory_hostname in groups['wazuh-manager'] }
    - { role: install_wazuh, when: inventory_hostname in groups['wazuh-manager'] }
