---
- name: Install Wazuh
  hosts: all
  become: yes

  pre_tasks:

    - name: Check if docker is installed
      stat:
        path: /var/lib/docker
      register: docker_check

  roles:
    - { role: install_docker, when: (inventory_hostname == 'wazuh-manager') and (not docker_check.stat.exists) }
    - { role: install_wazuh, when: inventory_hostname == 'wazuh-manager' }
    - { role: install_wazuh_agent, when: inventory_hostname == 'wazuh-agent' }
