---
- name: Install Wazuh server
  hosts: wazuh-manger
  become: yes

  pre_tasks:

    - name: Check if docker is installed
      stat:
        path: /var/lib/docker
      register: docker_check

  roles:
    - { role: install_docker, when: not docker_check.stat.exists }
    - install_wazuh

- name: Install Wazuh agent
  hosts: wazuh-agent
  become: yes

  roles:
    - role: install_wazuh_agent
