---
- name: Install Docker
  hosts: all
  become: yes

  roles:
    - { role: install_docker, when: 'master' in inventory_hostname }
    - { role: install_wazuh, when: 'master' in inventory_hostname }
