---
- name: Update repo's and upgrade components
  apt:
    update_cache: yes
    name: "*"
    state: latest

- name: Install repo's instruments
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add keyrings dir
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.gpg

- name: Set permissions for Docker GPG key
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'

- name: Add Docker apt repository
  become: true
  apt_repository:
    update_cache: yes
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: Install Docker packages
  become: true
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-buildx-plugin
    state: present

#- name: Add user to Docker group #Not recommended
#  become: true
#  user:
#    name: '{{ lookup('ansible.builtin.env', 'USER') }}'
#    groups: docker
#    append: yes
#  ignore_errors: true